name: Update custom hosts

on:
#  push:
#    branches: [ "master" ]
  schedule:
    - cron: '0 0-23/2 * * *'
  workflow_dispatch:
    inputs:
      domain_list:
        description: '域名数组（json字符串格式）'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -qr requirements.txt

      - name: Update hosts
        run: |
          domain_list='${{ github.event.inputs.domain_list }}'
          python main.py '${{ secrets.BASE_DATA }}' $domain_list
